# -*- coding: utf-8 -*-
"""Capitalize_words

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H2LWTE4wtVBTX07xo1AySsXzPwEchncj
"""

#capitalizing the sentence after (., ?, !)

def capitalize():
  inp="hello I'm Tahmeed. i make python projects for fun? ahem! maybe?" #input()
  #capitalize after a full stop
  string=''
  store=inp.split('. ')
  for i in store:
    add=i[0].upper() + i[1:] + '. '
    string+=add

  #capitalize after a question mark
  string2=''
  store2=string.split('? ')
  for j in store2:
    add2=j[0].upper() + j[1:] + '? '
    string2+=add2

  #capitalize after a exclamation mark
  string3=''
  store3=string2.split('! ')
  for k in store3:
    add3=k[0].upper() + k[1:] + '! '
    string3+=add3

  #removal of the additional punctuation   
  string4=string3[:len(string3)-6]
  print(string4)

capitalize()